### ISSUE TITLE
on/off option for scrollTo

### ISSUE THREAD

**Issue by chrtz** [arodax/vue-nav-spa#1]
First things first – I highly appreciate your work. this is the first approach which is finally working in my project. It's deadly simple to handle and straightforward.

I’d just like to ask for an upcoming feature:
Option to disable all the scrollTo features. In my case the CSS property `scroll-behaviour: smooth;` would be totally enough.

Regards

**Comment by cur53se** [comment]
Hi thanks for your feedback, really appreciated that you like this package!

About the feature request. You would like to have an option to disable the "smooth scroll" but keep the "spy scroll" (adding active class on menu when scrolling over section) feature? Am I right?

**Comment by chrtz** [comment]
Exactly.
Having all the smooth scroll/scrollTo features optional would be a huge benefit.
Navspa would be even more flexible.

**Comment by cur53se** [comment]
Added in `1.2.0` you can use it as:
```
<nav-spa :enabled-smooth-scroll="false"> 
```
which disables smooth scroll but keep the spy scroll. Check if it works, as you expected! :)

**Comment by chrtz** [comment]
I wasn’t able to spot a difference, yet. Will have a look during the weekend. Thank you tons.

**Comment by chrtz** [comment]
I updated the package and tried to use the `enable-smooth-scroll` but whether I switch it to true/false, I doesn’t change anything, yet. It’s still enabled.

**Comment by cur53se** [comment]
Hi chrtz!

Sorry It seems I haven't seen your reply in this thread. Have you managed to get this worked?

**Comment by chrtz** [comment]
Totally forgot abut this - I think I used CSS smooth-scroll instead.

**Comment by chrtz** [comment]
Totally forgot abut this - I think I used CSS smooth-scroll instead.

*EDIT:* I double checked it again, it's working for sure now!
